name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure this matches your project’s Node.js version

      - name: Install Dependencies
        run: npm install  # or yarn install if you use Yarn

      - name: Build React App
        run: npm run build  # or yarn build
        env:
          CI: false  # Prevents React build warnings from breaking CI

      - name: Debug Built Files
        run: |
          echo "Listing built files..."
          ls -R dist/

      - name: Deploy Frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*"
          target: "/home/trentynnicholas-boogieboys/htdocs/boogieboys.trentynnicholas.com/"
          strip_components: 0
      
          rm: true
