name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Repository Files
        run: |
          echo "Listing all files..."
          ls -R FrontEnd/registerFrontEnd/dist/

      - name: Deploy Frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "FrontEnd/registerFrontEnd/dist/*"
          target: "/home/boogieboys/htdocs/boogieboys.one/"
          strip_components: 3
          rm: true

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Backend to VPS (Exclude upload directories)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Backend/*"
          target: "/home/boogieboys-api/htdocs/api.boogieboys.one/backend/"
          strip_components: 1
          rsync_opts: "--exclude=uploads/ --exclude=socialIcons/ --exclude=galleryuploads/"

      - name: Ensure upload folders exist on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Ensuring upload directories exist..."
            mkdir -p /home/boogieboys-api/htdocs/api.boogieboys.one/backend/uploads
            mkdir -p /home/boogieboys-api/htdocs/api.boogieboys.one/backend/socialIcons
            mkdir -p /home/boogieboys-api/htdocs/api.boogieboys.one/backend/galleryuploads
            chmod -R 755 /boogieboys-api/htdocs/api.boogieboys.one/backend/uploads
            chmod -R 755 /boogieboys-api/htdocs/api.boogieboys.one/backend/socialIcons
            chmod -R 755 /boogieboys-api/htdocs/api.boogieboys.one/backend/galleryuploads
            echo "All upload directories ensured on VPS."

      - name: Install Dependencies on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Installing dependencies..."
            cd /home/boogieboys-api/htdocs/api.boogieboys.one/backend
            npm install --production
            echo "Restarting backend service..."
#            pm2 restart bakersburns

      - name: Restart Backend Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Restarting backend service..."
#            pm2 restart bakersburns


  